### ISSUE TITLE
Settings and File Upload feature

### ISSUE THREAD

**Issue by blvckrvy** [blvckrvy/Worker-Unity#5]
Complete the settings page and the file upload feature

**Comment by Tsholo-Tee** [comment]
The xaml code of it<?xml version="1.0" encoding="utf-8" ?><ContentPage xmlns="http://xamarin.com/schemas/2014/forms"             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"             x:Class="UploadFile.MainPage"             Title="File Picker">     <StackLayout Padding="20" VerticalOptions="Center">                <Button             Text="Upload File"             Clicked="OnCounterClicked"             HorizontalOptions="Center"             VerticalOptions="Center"            WidthRequest="100"            HeightRequest="40"            BackgroundColor="#4CAF50"            TextColor="White"            CornerRadius="10"/>                 <Image             x:Name="ImageLabel"             HeightRequest="200"             WidthRequest="200"             Aspect="AspectFit"             VerticalOptions="Center"             HorizontalOptions="Center" />    </StackLayout></ContentPage> The the cs code of it namespace UploadFile{    public partial class MainPage : ContentPage    {         public MainPage()        {            InitializeComponent();        }         private async void OnCounterClicked(object sender, EventArgs e)        {            var response = await FilePicker.PickAsync(new PickOptions            {                PickerTitle = " Please select a file to upload",                FileTypes = FilePickerFileType.Images            });            if (response.FileName.EndsWith("jpg", StringComparison.OrdinalIgnoreCase) || response.FileName.EndsWith("png", StringComparison.OrdinalIgnoreCase))            {                var stream = await response.OpenReadAsync();                ImageLabel.Source = ImageSource.FromStream(() => stream);                await Shell.Current.DisplayAlert("Info", response.FullPath, "OK");                await Task.Delay(2000);            }            else            {                await Shell.Current.DisplayAlert("Alert", "Invalid file selected", "Ok");            }        }    } } I hope it works Sent from Mail for Windows From: blvckrvySent: Saturday, 16 November 2024 20:57To: blvckrvy/Worker-UnityCc: Tsholofelo Rocsta; AssignSubject: [blvckrvy/Worker-Unity] Settings and File Upload feature (Issue #5) Complete the settings page and the file upload feature—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
